package com.example.demo.controller;

import com.example.demo.bean.Transactions;


rule "Remove Not Matched Name Transactions"

	salience 1000
	auto-focus true
	
	when
		$transactions : Transactions($id : id);
		not Transactions($id == id, name matches "Equity|expenses");		
	then
		retract($transactions);
end

rule "Remove No Type Transactions"

	salience 900
	auto-focus true
	
	when
		$transactions : Transactions($id : id);
		eval($transactions.getType() == null );	
	then
		retract($transactions);
end

rule "Remove amount1 < 0 Transactions"

	salience 800
	auto-focus true
	
	when
		$transactions : Transactions($id : id);
		exists Transactions($id == id, amount1 < 0);		
	then
		retract($transactions);
end

rule "Sum amount"

	salience 600
	auto-focus true
	
	when
		$transactions : Transactions($id : id);		
	then
		modify($transactions){
			setAmount($transactions.getAmount1() + $transactions.getAmount2() + $transactions.getAmount3());
		}
end